version: '3'

services:
  
  back:
    container_name: back
    build: 
      context: Market.Back
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS : 'http://0.0.0.0:5000'
      Host :  'database'
      Port :  '5432'
      Password : '1'
      Username : 'postgres'
    depends_on:
      - database
    ports:
      - "5000"
  front:
    container_name: front
    build: 
      context: Market.Front/Market
      dockerfile: Dockerfile
    depends_on:
      - back
    volumes:
      -  ./assets:/usr/share/nginx/html/assets
    depends_on:
      - back

    links:
      - back
 
    ports:
      - "82:90"
    environment:
      - NGINX_PORT=90 
      
  database:
    image: postgres:14
    container_name: database
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : '1'
      POSTGRES_USER : 'postgres'
  
  
  
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - front
      - back      
    links:
      - front
      - back       
 
  
 
